Repository Yamato-Security/suzaku-rules, pull requests merged in 2025-04, with the labels that each got.

#22 automerge with kodiak
  .github/.kodiak.toml
Labels: bug

#24 dont explicitly auto approve
  .github/workflows/update-sigmarule.yaml
Labels: bug

#25 update readme
  README-Japanese.md
  README.md
Labels: documentation

#27 Add functionality to ignore upstream sigma rules
  .github/workflows/update-sigmarule.yaml
  config/default_details.txt
  config/filtered_sigma_rules.txt
Labels: enhancement

#30 add rules 2025-04-23
  suzaku/aws_cloudtrail_api_created.yml
  suzaku/aws_cloudtrail_attempt_to_create_api_key.yml
  suzaku/aws_cloudtrail_attempt_to_delete_logs.yml
  suzaku/aws_cloudtrail_attempt_to_get_credentials_for_identity.yml
  suzaku/aws_cloudtrail_attempt_to_get_federation_token.yml
  suzaku/aws_cloudtrail_attempt_to_get_signin_token.yml
  suzaku/aws_cloudtrail_attempt_to_modify_log_settings.yml
  suzaku/aws_cloudtrail_attempt_to_stop_logging.yml
  suzaku/aws_cloudtrail_get_credentials_for_identity.yml
  suzaku/aws_cloudtrail_get_federation_token.yml
  suzaku/aws_cloudtrail_get_signin_token.yml
  suzaku/aws_cloudtrail_log_settings_modified.yml
  suzaku/aws_cloudtrail_logging_stopped.yml
  suzaku/aws_cloudtrail_logs_deleted.yml
Labels: enhancement
